# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ac507c57b3e66c9548d556f3b9fdb20bd344dbaa6b4daa855fbbb680ecc6f69531112ba4eeeddbf5a9986af5099cff5c061a0e5866d05cab147c0df20b1837f

test:
  secret_key_base: cfff79cf68952cd003d2a76ae18ea42dc54c26e14e0b1f794a7cab5303681834e77d5fcb48f9e9218cf8e2a420a00105b121292e93f5a444e64400a980ea0233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
